/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FavoritesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian21 = require("obsidian");

// src/commands/ClearPluginFavoritesList.ts
var import_obsidian2 = require("obsidian");

// src/modals/DialogModal.ts
var import_obsidian = require("obsidian");
var DialogModal = class extends import_obsidian.Modal {
  constructor(app, title, message, onSubmit, onDeny, submit = "Agree", submitWarning = false, deny = "Cancel", denyWarning = true) {
    super(app);
    this.titleEl.setText(title);
    this.message = message;
    this.onSubmit = onSubmit;
    this.onDeny = onDeny;
    this.submit = submit;
    this.submitWarning = submitWarning;
    this.deny = deny;
    this.denyWarning = denyWarning;
  }
  onOpen() {
    const { contentEl } = this;
    if (this.message && this.message !== "") {
      contentEl.createEl("span", { text: this.message });
    }
    const setting = new import_obsidian.Setting(contentEl);
    if (this.submitWarning) {
      setting.addButton((button) => button.setButtonText(this.submit).setWarning().onClick(() => {
        this.close();
        this.onSubmit();
      }));
    } else {
      setting.addButton((button) => button.setButtonText(this.submit).onClick(() => {
        this.close();
        this.onSubmit();
      }));
    }
    if (this.denyWarning) {
      setting.addButton((button) => button.setButtonText(this.deny).setWarning().onClick(() => {
        this.close();
        this.onDeny();
      }));
    } else {
      setting.addButton((button) => button.setButtonText(this.deny).onClick(() => {
        this.close();
        this.onDeny();
      }));
    }
    setting.setClass("modal-buttons");
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/commands/ClearPluginFavoritesList.ts
function ClearPluginFavoritesList_default(plugin) {
  return {
    id: "clear-plugin-favorites-list",
    name: "Clear the plugin favorites list",
    callback: () => {
      plugin.loadFavoritePlugins();
      const numberClear = plugin.favoritePlugins.length;
      new DialogModal(plugin.app, `Clear ${numberClear} plugin(s) permanently from favorite list?`, "", () => {
        plugin.favoritePlugins = [];
        plugin.saveFavoritePlugins();
        new import_obsidian2.Notice(`Cleared ${numberClear} plugins from favorite list`);
      }, () => {
        new import_obsidian2.Notice("Canceled clear plugins from favorite list");
      }, "Clear", true, "Cancel", false).open();
    }
  };
}

// src/commands/ClearPluginInUseList.ts
var import_obsidian3 = require("obsidian");
function ClearPluginInUseList_default(plugin) {
  return {
    id: "clear-plugin-in-use-list",
    name: "Clear the plugin in use list",
    callback: () => {
      plugin.loadInUsePlugins();
      const numberClear = Object.keys(plugin.inUsePlugins).length;
      new DialogModal(plugin.app, `Clear ${numberClear} plugin(s) permanently from in use list?`, "", () => {
        plugin.inUsePlugins = {};
        plugin.saveInUsePlugins();
        new import_obsidian3.Notice(`Cleared ${numberClear} plugins from in use list`);
      }, () => {
        new import_obsidian3.Notice("Canceled clear plugins from in use list");
      }, "Clear", true, "Cancel", false).open();
    }
  };
}

// src/commands/ClearPluginKnownList.ts
var import_obsidian4 = require("obsidian");
function ClearPluginKnownList_default(plugin) {
  return {
    id: "clear-plugin-known-list",
    name: "Clear the plugin known list",
    callback: () => {
      plugin.loadKnownPlugins();
      const numberClear = plugin.knownPlugins.length;
      new DialogModal(plugin.app, `Clear ${numberClear} plugin(s) permanently from known list?`, "", () => {
        plugin.knownPlugins = [];
        plugin.saveKnownPlugins();
        new import_obsidian4.Notice(`Cleared ${numberClear} plugins from known list`);
      }, () => {
        new import_obsidian4.Notice("Canceled clear plugins from known list");
      }, "Clear", true, "Cancel", false).open();
    }
  };
}

// src/commands/ClearThemeFavoritesList.ts
var import_obsidian5 = require("obsidian");
function ClearThemeFavoritesList_default(plugin) {
  return {
    id: "clear-theme-favorites-list",
    name: "Clear the theme favorites list",
    callback: () => {
      plugin.loadFavoriteThemes();
      const numberClear = plugin.favoriteThemes.length;
      new DialogModal(plugin.app, `Clear ${numberClear} theme(s) permanently from favorite list?`, "", () => {
        plugin.favoriteThemes = [];
        plugin.saveFavoriteThemes();
        new import_obsidian5.Notice(`Cleared ${numberClear} themes from favorite list`);
      }, () => {
        new import_obsidian5.Notice("Canceled clear themes from favorite list");
      }, "Clear", true, "Cancel", false).open();
    }
  };
}

// src/commands/ClearThemeInUseList.ts
var import_obsidian6 = require("obsidian");
function ClearThemeInUseList_default(plugin) {
  return {
    id: "clear-theme-in-use-list",
    name: "Clear the theme in use list",
    callback: () => {
      plugin.loadInUseThemes();
      const numberClear = Object.keys(plugin.inUseThemes).length;
      new DialogModal(plugin.app, `Clear ${numberClear} theme(s) permanently from in use list?`, "", () => {
        plugin.inUseThemes = {};
        plugin.saveInUseThemes();
        new import_obsidian6.Notice(`Cleared ${numberClear} themes from in use list`);
      }, () => {
        new import_obsidian6.Notice("Canceled clear themes from in use list");
      }, "Clear", true, "Cancel", false).open();
    }
  };
}

// src/commands/ClearThemeKnownList.ts
var import_obsidian7 = require("obsidian");
function ClearThemeKnownList_default(plugin) {
  return {
    id: "clear-theme-known-list",
    name: "Clear the theme known list",
    callback: () => {
      plugin.loadKnownThemes();
      const numberClear = plugin.knownThemes.length;
      new DialogModal(plugin.app, `Clear ${numberClear} theme(s) permanently from known list?`, "", () => {
        plugin.knownThemes = [];
        plugin.saveKnownThemes();
        new import_obsidian7.Notice(`Cleared ${numberClear} themes from known list`);
      }, () => {
        new import_obsidian7.Notice("Canceled clear themes from known list");
      }, "Clear", true, "Cancel", false).open();
    }
  };
}

// src/commands/ExportLists.ts
var import_obsidian8 = require("obsidian");

// src/constants.ts
var PLUGIN_ID = "favorites";
var PLUGIN_BACKUP_BASE_PATH = `/plugins/${PLUGIN_ID}/backup`;

// src/commands/ExportLists.ts
function ExportLists_default(plugin) {
  return {
    id: "export-lists",
    name: "Export lists to file",
    callback: async () => {
      if (plugin.favoritePlugins.length <= 0 && plugin.favoriteThemes.length <= 0 && Object.keys(plugin.inUsePlugins).length <= 0 && Object.keys(plugin.inUseThemes).length <= 0 && plugin.knownPlugins.length <= 0 && plugin.knownThemes.length <= 0) {
        new import_obsidian8.Notice("No lists to backup");
        return;
      }
      const backupPath = (0, import_obsidian8.normalizePath)(`${plugin.app.vault.configDir}${PLUGIN_BACKUP_BASE_PATH}`);
      await plugin.app.vault.adapter.mkdir(backupPath);
      const pad = (n) => n.toString().padStart(2, "0");
      const date = /* @__PURE__ */ new Date();
      const dateString = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}-${pad(date.getHours())}-${pad(date.getMinutes())}`;
      const backupFilePath = (0, import_obsidian8.normalizePath)(`${backupPath}/favorite-${dateString}.json`);
      await plugin.app.vault.adapter.write(backupFilePath, JSON.stringify({
        favoritePlugins: plugin.favoritePlugins,
        favoriteThemes: plugin.favoriteThemes,
        inUsePlugins: plugin.inUsePlugins,
        inUseThemes: plugin.inUseThemes,
        knownPlugins: plugin.knownPlugins,
        knownThemes: plugin.knownThemes
      }));
      new import_obsidian8.Notice(`Lists backup successful written to: ${backupFilePath}`);
    }
  };
}

// src/commands/ImportLists.ts
var import_obsidian10 = require("obsidian");

// src/modals/StringSuggestModal.ts
var import_obsidian9 = require("obsidian");
var StringSuggestModal = class extends import_obsidian9.FuzzySuggestModal {
  constructor(app, title, items, onSubmit) {
    super(app);
    this.items = [];
    this.onSubmit = () => {
    };
    this.setPlaceholder(title);
    this.items = items;
    this.onSubmit = onSubmit;
  }
  getItems() {
    return this.items;
  }
  getItemText(item) {
    return item;
  }
  onChooseItem(item) {
    this.onSubmit(item);
  }
};

// src/commands/ImportLists.ts
function ImportLists_default(plugin) {
  return {
    id: "import-lists",
    name: "Import lists from file",
    callback: async () => {
      const backupPath = (0, import_obsidian10.normalizePath)(`${plugin.app.vault.configDir}${PLUGIN_BACKUP_BASE_PATH}`);
      if (!await plugin.app.vault.adapter.exists(backupPath)) {
        new import_obsidian10.Notice(`Backup path does not exist: ${backupPath}`);
        return;
      }
      const backupFiles = (await plugin.app.vault.adapter.list(backupPath)).files;
      if (backupFiles.length <= 0) {
        new import_obsidian10.Notice("Backup path is empty");
        return;
      }
      new StringSuggestModal(plugin.app, "Select backup file to load from", backupFiles, async (result) => {
        const content = await plugin.app.vault.adapter.read(result);
        const json = JSON.parse(content);
        const loadedFavoritePlugins = json.favoritePlugins || [];
        const loadedFavoriteThemes = json.favoriteThemes || [];
        const loadedInUsePlugins = json.inUsePlugins || [];
        const loadedInUseThemes = json.inUseThemes || [];
        const loadedKnownPlugins = json.knownPlugins || [];
        const loadedKnownThemes = json.knownThemes || [];
        new DialogModal(plugin.app, "Are you sure you want to overwrite current lists?", `The following lists will be overwritten: favorite plugins will change from ${plugin.favoritePlugins.length} items to ${loadedFavoritePlugins.length} items, favorite themes will change from ${plugin.favoriteThemes.length} items to ${loadedFavoriteThemes.length} items, in use plugins will change from ${plugin.inUsePlugins.length} items to ${loadedInUsePlugins.length} items, in use themes will change from ${plugin.inUseThemes.length} items to ${loadedInUseThemes.length} items, known plugins will change from ${plugin.knownPlugins.length} items to ${loadedKnownPlugins.length} items, and known themes will change from ${plugin.knownThemes.length} items to ${loadedKnownThemes.length} items.`, () => {
          plugin.favoritePlugins = loadedFavoritePlugins;
          plugin.favoriteThemes = loadedFavoriteThemes;
          plugin.inUsePlugins = loadedInUsePlugins;
          plugin.inUseThemes = loadedInUseThemes;
          plugin.knownPlugins = loadedKnownPlugins;
          plugin.knownThemes = loadedKnownThemes;
          plugin.saveLists();
          new import_obsidian10.Notice("Loaded backup successfully");
        }, () => {
          new import_obsidian10.Notice("Canceled loading backup by user");
        }, "Overwrite", true, "Cancel", false).open();
      }).open();
    }
  };
}

// src/commands/LoadLists.ts
var import_obsidian11 = require("obsidian");
function LoadLists_default(plugin) {
  return {
    id: "load-lists",
    name: "Manually load the lists",
    callback: () => {
      plugin.loadLists();
      new import_obsidian11.Notice("Loaded lists");
    }
  };
}

// src/commands/SaveLists.ts
var import_obsidian12 = require("obsidian");
function SaveLists_default(plugin) {
  return {
    id: "save-lists",
    name: "Manually save the lists",
    callback: () => {
      plugin.saveLists();
      new import_obsidian12.Notice("Saved lists");
    }
  };
}

// src/commands/SearchAndAddPluginToFavoriteList.ts
var import_obsidian15 = require("obsidian");

// src/modals/CommunitySuggestModal.ts
var import_obsidian13 = require("obsidian");
var CommunitySuggestModal = class extends import_obsidian13.FuzzySuggestModal {
  constructor(app, title, items, onSubmit) {
    super(app);
    this.items = [];
    this.onSubmit = () => {
    };
    this.setPlaceholder(title);
    this.items = items;
    this.onSubmit = onSubmit;
  }
  getItemText(item) {
    return `${item.name} ${item.author}`;
  }
  getItems() {
    return this.items;
  }
  onChooseItem(item) {
    this.onSubmit(item);
  }
  renderSuggestion(match, el) {
    const titleEl = el.createDiv();
    (0, import_obsidian13.renderResults)(titleEl, match.item.name, match.match);
    const authorEl = el.createEl("small");
    const offset = -(match.item.name.length + 1);
    (0, import_obsidian13.renderResults)(authorEl, match.item.author, match.match, offset);
  }
};

// src/util/GitHub.ts
var import_obsidian14 = require("obsidian");
async function fetchCommunityPluginList() {
  const URL = "https://raw.githubusercontent.com/obsidianmd/obsidian-releases/HEAD/community-plugins.json";
  try {
    const response = await (0, import_obsidian14.request)({ url: URL });
    return await JSON.parse(response);
  } catch (e) {
    e.message = "Failed to fetch community plugin list! " + e.message;
    console.error(e);
  }
}
async function fetchCommunityThemeList() {
  const URL = "https://raw.githubusercontent.com/obsidianmd/obsidian-releases/refs/heads/master/community-css-themes.json";
  try {
    const response = await (0, import_obsidian14.request)({ url: URL });
    return await JSON.parse(response);
  } catch (e) {
    e.message = "Failed to fetch community plugin list! " + e.message;
    console.error(e);
  }
}

// src/commands/SearchAndAddPluginToFavoriteList.ts
function SearchAndAddPluginToFavoriteList_default(plugin) {
  return {
    id: "search-and-add-plugin-to-favorite-list",
    name: "Search and add plugin to favorite list",
    callback: async () => {
      let items = await fetchCommunityPluginList();
      if (!items) {
        new import_obsidian15.Notice("Failed to fetch community plugins. See console for more information.");
        return;
      }
      plugin.loadFavoritePlugins();
      items = items.filter((value) => !plugin.favoritePlugins.contains(value.id));
      if (items.length <= 0) {
        new import_obsidian15.Notice("No plugin left which is could be added to favorite list");
        return;
      }
      new CommunitySuggestModal(plugin.app, "Select plugin which should be added to favorites list...", items, (result) => {
        plugin.favoritePlugins.push(result.id);
        plugin.saveFavoritePlugins();
        new import_obsidian15.Notice(`Added ${result.name} to favorite list`);
      }).open();
    }
  };
}

// src/commands/SearchAndAddThemeToFavoriteList.ts
var import_obsidian16 = require("obsidian");
function SearchAndAddThemeToFavoriteList_default(plugin) {
  return {
    id: "search-and-add-theme-to-favorite-list",
    name: "Search and add theme to favorite list",
    callback: async () => {
      let items = await fetchCommunityThemeList();
      if (!items) {
        new import_obsidian16.Notice("Failed to fetch community themes. See console for more information.");
        return;
      }
      plugin.loadFavoriteThemes();
      items = items.filter((value) => !plugin.favoriteThemes.contains(value.name));
      if (items.length <= 0) {
        new import_obsidian16.Notice("No theme left which is could be added to favorite list");
        return;
      }
      new CommunitySuggestModal(plugin.app, "Select theme which should be added to favorites list...", items, (result) => {
        plugin.favoriteThemes.push(result.name);
        plugin.saveFavoriteThemes();
        new import_obsidian16.Notice(`Added ${result.name} to favorite list`);
      }).open();
    }
  };
}

// src/commands/SearchAndRemovePluginFromFavoriteList.ts
var import_obsidian17 = require("obsidian");
function SearchAndRemovePluginFromFavoriteList_default(plugin) {
  return {
    id: "search-and-remove-plugin-from-favorite-list",
    name: "Search and remove plugin from favorite list",
    callback: async () => {
      plugin.loadFavoritePlugins();
      if (plugin.favoritePlugins.length <= 0) {
        new import_obsidian17.Notice("Plugin favorite list is empty");
        return;
      }
      const communityItems = await fetchCommunityPluginList();
      const installedItems = Object.values(plugin.app.plugins.manifests);
      const items = plugin.favoritePlugins.map((value) => {
        return (communityItems == null ? void 0 : communityItems.find((communityValue) => value === communityValue.id)) || installedItems.find((installedValue) => value === installedValue.id) || { id: value, name: value, author: "unknown" };
      });
      new CommunitySuggestModal(plugin.app, "Select plugin which should be removed from the favorites list...", items, (result) => {
        plugin.favoritePlugins.remove(result.id);
        plugin.saveFavoritePlugins();
        new import_obsidian17.Notice(`Removed ${result.name} from favorite list`);
      }).open();
    }
  };
}

// src/commands/SearchAndRemoveThemeFromFavoriteList.ts
var import_obsidian18 = require("obsidian");
function SearchAndRemoveThemeFromFavoriteList_default(plugin) {
  return {
    id: "search-and-remove-theme-from-favorite-list",
    name: "Search and remove theme from favorite list",
    callback: async () => {
      plugin.loadFavoriteThemes();
      if (plugin.favoriteThemes.length <= 0) {
        new import_obsidian18.Notice("Theme favorite list is empty");
        return;
      }
      const communityItems = await fetchCommunityThemeList();
      const installedItems = Object.values(plugin.app.customCss.themes);
      const items = plugin.favoriteThemes.map((value) => {
        return (communityItems == null ? void 0 : communityItems.find((communityValue) => value === communityValue.name)) || installedItems.find((installedValue) => value === installedValue.name) || { name: value, author: "unknown" };
      });
      new CommunitySuggestModal(plugin.app, "Select theme which should be removed from the favorites list...", items, (result) => {
        plugin.favoriteThemes.remove(result.name);
        plugin.saveFavoriteThemes();
        new import_obsidian18.Notice(`Removed ${result.name} from favorite list`);
      }).open();
    }
  };
}

// src/commands/index.ts
async function addAllCommands(plugin) {
  plugin.addCommand(ClearPluginFavoritesList_default(plugin));
  plugin.addCommand(ClearPluginInUseList_default(plugin));
  plugin.addCommand(ClearPluginKnownList_default(plugin));
  plugin.addCommand(ClearThemeFavoritesList_default(plugin));
  plugin.addCommand(ClearThemeInUseList_default(plugin));
  plugin.addCommand(ClearThemeKnownList_default(plugin));
  plugin.addCommand(ExportLists_default(plugin));
  plugin.addCommand(ImportLists_default(plugin));
  plugin.addCommand(LoadLists_default(plugin));
  plugin.addCommand(SaveLists_default(plugin));
  plugin.addCommand(SearchAndAddPluginToFavoriteList_default(plugin));
  plugin.addCommand(SearchAndAddThemeToFavoriteList_default(plugin));
  plugin.addCommand(SearchAndRemovePluginFromFavoriteList_default(plugin));
  plugin.addCommand(SearchAndRemoveThemeFromFavoriteList_default(plugin));
}

// node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}
function dedupe(key, oldFn, newFn) {
  check[key] = key;
  return check;
  function check(...args) {
    return (oldFn[key] === key ? oldFn : newFn).apply(this, args);
  }
}

// src/patches/patch.CommunityPluginsSettingTab.ts
var import_obsidian19 = require("obsidian");
var MONKEY_KEY = `${PLUGIN_ID}-CommunityPluginsSettingTab-`;
var patch_CommunityPluginsSettingTab_default = (context, plugin) => around(context, {
  renderInstalledPlugin(oldMethod) {
    return dedupe(`${MONKEY_KEY}renderInstalledPlugin`, oldMethod, function(item, containerEl, n, i, r) {
      var _a;
      oldMethod && oldMethod.apply(this, [item, containerEl, n, i, r]);
      plugin.loadFavoritePlugins();
      const selectedPluginID = item.id;
      const isFavorite = plugin.favoritePlugins.contains(selectedPluginID);
      const favEl = createDiv("clickable-icon extra-setting-button");
      plugin.registerDomEvent(favEl, "click", () => {
        if (isFavorite) {
          plugin.favoritePlugins.remove(selectedPluginID);
        } else {
          plugin.favoritePlugins.push(selectedPluginID);
        }
        plugin.saveFavoritePlugins();
        this.render(false);
      });
      if (isFavorite) {
        (0, import_obsidian19.setIcon)(favEl, "star-off");
        (0, import_obsidian19.setTooltip)(favEl, "Unfavorite");
      } else {
        (0, import_obsidian19.setIcon)(favEl, "star");
        (0, import_obsidian19.setTooltip)(favEl, "Favorite");
      }
      const controlEl = (_a = this.installedPlugins.listEl.lastChild) == null ? void 0 : _a.getElementsByClassName("setting-item-control")[0];
      controlEl.insertBefore(favEl, controlEl.children[0]);
    });
  }
});

// src/patches/patch.SettingsModal.ts
var MONKEY_KEY2 = `${PLUGIN_ID}-SettingsModal-`;
var patch_SettingsModal_default = (plugin) => around(plugin.app.setting, {
  openTab(oldMethod) {
    return dedupe(`${MONKEY_KEY2}openTab`, oldMethod, function(tab) {
      if (tab.id === "community-plugins") {
        if (!plugin.uninstallCommunityPluginsSettingTabPatch) {
          plugin.uninstallCommunityPluginsSettingTabPatch = patch_CommunityPluginsSettingTab_default(tab, plugin);
        }
      }
      if (plugin.uninstallSettingsModalPatch && plugin.uninstallCommunityPluginsSettingTabPatch) {
        plugin.uninstallSettingsModalPatch();
        plugin.uninstallSettingsModalPatch = void 0;
      }
      return oldMethod && oldMethod.apply(this, [tab]);
    });
  }
});

// src/patches/patch.Modal.ts
var import_obsidian20 = require("obsidian");

// src/ui-components/Flair.ts
var Flair = class {
  constructor(parentEl, text, ariaLabel = null) {
    if (parentEl) {
      const flair = parentEl.createSpan({
        cls: "flair",
        text
      });
      if (ariaLabel) {
        flair.setAttribute("aria-label", ariaLabel);
      }
    }
  }
};

// src/ui-components/FavoriteFlair.ts
var FavoriteFlair = class extends Flair {
  constructor(parentEl) {
    super(parentEl, "Favorite", "Marked as favorite");
  }
};

// src/ui-components/InUseFlair.ts
var InUseFlair = class extends Flair {
  constructor(parentEl) {
    super(parentEl, "In Use", "Enabled in at least one vault");
  }
};

// src/ui-components/KnownFlair.ts
var KnownFlair = class extends Flair {
  constructor(parentEl) {
    super(parentEl, "Known", "Installed at least once in a vault");
  }
};

// src/ui-components/InstalledFlair.ts
var InstalledFlair = class {
  constructor(parentEl) {
    if (parentEl) {
      const flair = Array.from(parentEl.getElementsByClassName("flair")).find((el) => {
        var _a;
        return ((_a = el.textContent) == null ? void 0 : _a.trim().toLowerCase()) === "installed";
      });
      if (flair) {
        flair.setAttribute("aria-label", "Installed in this vault");
      }
    }
  }
};

// src/patches/patch.CommunityPluginModal.ts
var MONKEY_KEY3 = `${PLUGIN_ID}-CommunityPluginModal-`;
var patch_CommunityPluginModal_default = (context, plugin) => around(context.constructor.prototype, {
  showItem(oldMethod) {
    return dedupe(`${MONKEY_KEY3}showItem`, oldMethod, async function(item) {
      const result = oldMethod && await oldMethod.apply(this, [item]);
      const infoEl = await this.detailsEl.getElementsByClassName("community-modal-info")[0];
      const infoNameEl = await (infoEl == null ? void 0 : infoEl.getElementsByClassName("community-modal-info-name")[0]);
      const buttonContainerEl = await (infoEl == null ? void 0 : infoEl.getElementsByClassName("community-modal-button-container")[0]);
      plugin.loadFavoritePlugins();
      plugin.loadInUsePlugins();
      plugin.loadKnownPlugins();
      new InstalledFlair(infoNameEl);
      const isFavorite = plugin.favoritePlugins.contains(this.selectedItemId);
      if (isFavorite) {
        new FavoriteFlair(infoNameEl);
      }
      if (Object.keys(plugin.inUsePlugins).contains(this.selectedItemId)) {
        new InUseFlair(infoNameEl);
      }
      if (plugin.knownPlugins.contains(this.selectedItemId)) {
        new KnownFlair(infoNameEl);
      }
      plugin.registerDomEvent(buttonContainerEl == null ? void 0 : buttonContainerEl.createEl("button", { text: isFavorite ? "Unfavorite" : "Favorite" }), "click", async () => {
        if (isFavorite) {
          plugin.favoritePlugins.remove(this.selectedItemId);
        } else {
          plugin.favoritePlugins.push(this.selectedItemId);
        }
        plugin.saveFavoritePlugins();
        infoEl.detach();
        await this.showItem(this.items[this.selectedItemId]);
        this.update();
      });
      return result;
    });
  },
  updateItems(oldMethod) {
    return dedupe(`${MONKEY_KEY3}updateItems`, oldMethod, function() {
      plugin.loadFavoritePlugins();
      plugin.loadInUsePlugins();
      plugin.loadKnownPlugins();
      const result = oldMethod && oldMethod.apply(this);
      Object.keys(plugin.app.plugins.manifests).forEach((id) => {
        var _a;
        new InstalledFlair((_a = this.items[id]) == null ? void 0 : _a.nameEl);
      });
      plugin.favoritePlugins.forEach((id) => {
        var _a;
        new FavoriteFlair((_a = this.items[id]) == null ? void 0 : _a.nameEl);
      });
      Object.keys(plugin.inUsePlugins).forEach((id) => {
        var _a;
        new InUseFlair((_a = this.items[id]) == null ? void 0 : _a.nameEl);
      });
      plugin.knownPlugins.forEach((id) => {
        var _a;
        new KnownFlair((_a = this.items[id]) == null ? void 0 : _a.nameEl);
      });
      return result;
    });
  }
});

// src/ui-components/ActiveFlair.ts
var ActiveFlair = class {
  constructor(parentEl) {
    if (parentEl) {
      const flair = Array.from(parentEl.getElementsByClassName("flair")).find((el) => {
        var _a;
        return ((_a = el.textContent) == null ? void 0 : _a.trim().toLowerCase()) === "active";
      });
      if (flair) {
        flair.setAttribute("aria-label", "Active theme in this vault");
      }
    }
  }
};

// src/patches/patch.CommunityThemeModal.ts
var MONKEY_KEY4 = `${PLUGIN_ID}-ThemePluginModal-`;
var patch_CommunityThemeModal_default = (context, plugin) => around(context.constructor.prototype, {
  showItem(oldMethod) {
    return dedupe(`${MONKEY_KEY4}showItem`, oldMethod, async function(item) {
      const result = oldMethod && await oldMethod.apply(this, [item]);
      const infoEl = await this.detailsEl.getElementsByClassName("community-modal-info")[0];
      const infoNameEl = await (infoEl == null ? void 0 : infoEl.getElementsByClassName("community-modal-info-name")[0]);
      new InstalledFlair(infoNameEl);
      if (this.selectedItemId === "") {
        return result;
      }
      const buttonContainerEl = await (infoEl == null ? void 0 : infoEl.getElementsByClassName("community-modal-button-container")[0]);
      plugin.loadFavoriteThemes();
      plugin.loadInUseThemes();
      plugin.loadKnownThemes();
      const isFavorite = plugin.favoriteThemes.contains(this.selectedItemId);
      if (isFavorite) {
        new FavoriteFlair(infoNameEl);
      }
      if (Object.keys(plugin.inUseThemes).contains(this.selectedItemId)) {
        new InUseFlair(infoNameEl);
      }
      if (plugin.knownThemes.contains(this.selectedItemId)) {
        new KnownFlair(infoNameEl);
      }
      plugin.registerDomEvent(buttonContainerEl == null ? void 0 : buttonContainerEl.createEl("button", { text: isFavorite ? "Unfavorite" : "Favorite" }), "click", async () => {
        if (isFavorite) {
          plugin.favoriteThemes.remove(this.selectedItemId);
        } else {
          plugin.favoriteThemes.push(this.selectedItemId);
        }
        plugin.saveFavoriteThemes();
        infoEl.detach();
        await this.showItem(this.items[this.selectedItemId]);
        this.update();
      });
      return result;
    });
  },
  updateItems(oldMethod) {
    return dedupe(`${MONKEY_KEY4}updateItems`, oldMethod, function() {
      var _a;
      plugin.loadFavoriteThemes();
      plugin.loadInUseThemes();
      plugin.loadKnownThemes();
      const result = oldMethod && oldMethod.apply(this);
      Object.keys(plugin.app.customCss.themes).forEach((id) => {
        var _a2;
        new InstalledFlair((_a2 = this.items[id]) == null ? void 0 : _a2.nameEl);
      });
      new ActiveFlair((_a = this.items[plugin.app.customCss.theme]) == null ? void 0 : _a.nameEl);
      if (this.selectedItemId === "") {
        return result;
      }
      plugin.favoriteThemes.forEach((id) => {
        var _a2;
        new FavoriteFlair((_a2 = this.items[id]) == null ? void 0 : _a2.nameEl);
      });
      Object.keys(plugin.inUseThemes).forEach((id) => {
        var _a2;
        new InUseFlair((_a2 = this.items[id]) == null ? void 0 : _a2.nameEl);
      });
      plugin.knownThemes.forEach((id) => {
        var _a2;
        new KnownFlair((_a2 = this.items[id]) == null ? void 0 : _a2.nameEl);
      });
      return result;
    });
  }
});

// src/patches/patch.Modal.ts
var MONKEY_KEY5 = `${PLUGIN_ID}-Modal-`;
var patch_Modal_default = (plugin) => around(import_obsidian20.Modal.prototype, {
  open(oldMethod) {
    return dedupe(`${MONKEY_KEY5}open`, oldMethod, function() {
      var _a, _b;
      const result = oldMethod && oldMethod.apply(this);
      if ((_a = this.containerEl) == null ? void 0 : _a.querySelector(".mod-community-plugin")) {
        if (!plugin.uninstallCommunityPluginModalPatch) {
          plugin.uninstallCommunityPluginModalPatch = patch_CommunityPluginModal_default(this, plugin);
        }
      }
      if ((_b = this.containerEl) == null ? void 0 : _b.querySelector(".mod-community-theme")) {
        if (!plugin.uninstallCommunityThemeModalPatch) {
          plugin.uninstallCommunityThemeModalPatch = patch_CommunityThemeModal_default(this, plugin);
        }
      }
      if (plugin.uninstallModalPatch && plugin.uninstallCommunityPluginModalPatch && plugin.uninstallCommunityThemeModalPatch) {
        plugin.uninstallModalPatch();
        plugin.uninstallModalPatch = void 0;
      }
      return result;
    });
  }
});

// src/patches/patch.PluginManager.ts
var MONKEY_KEY6 = `${PLUGIN_ID}-PluginManager-`;
var patch_PluginManager_default = (plugin) => around(plugin.app.plugins, {
  installPlugin(oldMethod) {
    return dedupe(`${MONKEY_KEY6}installPlugin`, oldMethod, async function(repo, version, manifest) {
      const result = oldMethod && await oldMethod.apply(this, [repo, version, manifest]);
      plugin.loadKnownPlugins();
      if (!plugin.knownPlugins.contains(manifest.id)) {
        plugin.knownPlugins.push(manifest.id);
      }
      plugin.saveKnownPlugins();
      return result;
    });
  },
  loadPlugin(oldMethod) {
    return dedupe(`${MONKEY_KEY6}loadPlugin`, oldMethod, async function(id) {
      const currentVault = plugin.app.appId;
      plugin.loadInUsePlugins();
      if (!plugin.inUsePlugins[id] || !Array.isArray(plugin.inUsePlugins[id])) {
        plugin.inUsePlugins[id] = [];
      }
      if (!plugin.inUsePlugins[id].contains(currentVault)) {
        plugin.inUsePlugins[id].push(currentVault);
      }
      plugin.saveInUsePlugins();
      return oldMethod && oldMethod.apply(this, [id]);
    });
  },
  unloadPlugin(oldMethod) {
    return dedupe(`${MONKEY_KEY6}unloadPlugin`, oldMethod, async function(id) {
      const currentVault = plugin.app.appId;
      plugin.loadInUsePlugins();
      if (plugin.inUsePlugins[id] && Array.isArray(plugin.inUsePlugins[id]) && plugin.inUsePlugins[id].contains(currentVault)) {
        plugin.inUsePlugins[id].remove(currentVault);
        if (plugin.inUsePlugins[id].length <= 0) {
          delete plugin.inUsePlugins[id];
        }
      }
      plugin.saveInUsePlugins();
      return oldMethod && oldMethod.apply(this, [id]);
    });
  }
});

// src/patches/patch.StyleManager.ts
var MONKEY_KEY7 = `${PLUGIN_ID}-StyleManager-installTheme`;
var patch_StyleManager_default = (plugin) => around(plugin.app.customCss, {
  installTheme(oldMethod) {
    return dedupe(`${MONKEY_KEY7}installTheme`, oldMethod, async function(manifest, version) {
      const result = oldMethod && await oldMethod.apply(this, [manifest, version]);
      plugin.loadKnownThemes();
      if (!plugin.knownThemes.contains(manifest.name)) {
        plugin.knownThemes.push(manifest.name);
      }
      plugin.saveKnownThemes();
      return result;
    });
  },
  setTheme(oldMethod) {
    return dedupe(`${MONKEY_KEY7}setTheme`, oldMethod, function(name) {
      const currentVault = plugin.app.appId;
      plugin.loadInUseThemes();
      const oldTheme = this.theme;
      if (plugin.inUseThemes[oldTheme] && Array.isArray(plugin.inUseThemes[oldTheme]) && plugin.inUseThemes[oldTheme].contains(currentVault)) {
        plugin.inUseThemes[oldTheme].remove(currentVault);
        if (plugin.inUseThemes[oldTheme].length <= 0) {
          delete plugin.inUseThemes[oldTheme];
        }
      }
      const result = oldMethod && oldMethod.apply(this, [name]);
      if (name === "") {
        plugin.saveInUseThemes();
        return result;
      }
      if (!plugin.inUseThemes[name] || !Array.isArray(plugin.inUseThemes[name])) {
        plugin.inUseThemes[name] = [];
      }
      if (!plugin.inUseThemes[name].contains(currentVault)) {
        plugin.inUseThemes[name].push(currentVault);
      }
      plugin.saveInUseThemes();
      return result;
    });
  }
});

// src/main.ts
var FavoritesPlugin = class extends import_obsidian21.Plugin {
  async onload() {
    this.loadStorageKeys();
    this.loadLists();
    if (!this.uninstallSettingsModalPatch) {
      this.uninstallSettingsModalPatch = patch_SettingsModal_default(this);
    }
    if (!this.uninstallModalPatch) {
      this.uninstallModalPatch = patch_Modal_default(this);
    }
    if (!this.uninstallPluginManagerPatch) {
      this.uninstallPluginManagerPatch = patch_PluginManager_default(this);
    }
    if (!this.uninstallStyleManagerPatch) {
      this.uninstallStyleManagerPatch = patch_StyleManager_default(this);
    }
    this.updateListsForVault();
    addAllCommands(this);
  }
  async onunload() {
    try {
      if (this.uninstallCommunityPluginModalPatch) {
        this.uninstallCommunityPluginModalPatch();
        this.uninstallCommunityPluginModalPatch = void 0;
      }
      if (this.uninstallCommunityPluginsSettingTabPatch) {
        this.uninstallCommunityPluginsSettingTabPatch();
        this.uninstallCommunityPluginsSettingTabPatch = void 0;
      }
      if (this.uninstallCommunityThemeModalPatch) {
        this.uninstallCommunityThemeModalPatch();
        this.uninstallCommunityThemeModalPatch = void 0;
      }
      if (this.uninstallModalPatch) {
        this.uninstallModalPatch();
        this.uninstallModalPatch = void 0;
      }
      if (this.uninstallPluginManagerPatch) {
        this.uninstallPluginManagerPatch();
        this.uninstallPluginManagerPatch = void 0;
      }
      if (this.uninstallSettingsModalPatch) {
        this.uninstallSettingsModalPatch();
        this.uninstallSettingsModalPatch = void 0;
      }
      if (this.uninstallStyleManagerPatch) {
        this.uninstallStyleManagerPatch();
        this.uninstallStyleManagerPatch = void 0;
      }
    } catch (e) {
      console.error("Failed uninstalling patch functions!");
      console.error(e);
    }
  }
  loadStorageKeys() {
    if ("favorite-plugins") {
      this.pluginFavoritesKey = "favorite-plugins";
    } else {
      throw Error("Missing environment variable 'FAVORITE_PLUGINS_KEY'");
    }
    if ("favorite-themes") {
      this.themeFavoritesKey = "favorite-themes";
    } else {
      throw Error("Missing environment variable 'FAVORITE_THEMES_KEY'");
    }
    if ("in-use-plugins") {
      this.pluginInUseKey = "in-use-plugins";
    } else {
      throw Error("Missing environment variable 'INUSE_PLUGINS_KEY'");
    }
    if ("in-use-themes") {
      this.themeInUseKey = "in-use-themes";
    } else {
      throw Error("Missing environment variable 'INUSE_THEMES_KEY'");
    }
    if ("known-plugins") {
      this.pluginKnownKey = "known-plugins";
    } else {
      throw Error("Missing environment variable 'KNOWN_PLUGINS_KEY'");
    }
    if ("known-themes") {
      this.themeKnownKey = "known-themes";
    } else {
      throw Error("Missing environment variable 'KNOWN_THEMES_KEY'");
    }
    this.registerDomEvent(window, "storage", (event) => {
      if (event.key === this.pluginFavoritesKey) {
        this.onFavoritePluginsChanged(event.newValue);
      }
      if (event.key === this.themeFavoritesKey) {
        this.onFavoriteThemesChanged(event.newValue);
      }
      if (event.key === this.pluginInUseKey) {
        this.onInUsePluginsChanged(event.newValue);
      }
      if (event.key === this.themeInUseKey) {
        this.onInUseThemesChanged(event.newValue);
      }
      if (event.key === this.pluginKnownKey) {
        this.onKnownPluginsChanged(event.newValue);
      }
      if (event.key === this.themeKnownKey) {
        this.onKnownThemesChanged(event.newValue);
      }
    });
  }
  onFavoritePluginsChanged(newValue) {
    if (newValue) {
      this.favoritePlugins = JSON.parse(newValue);
    } else {
      this.favoritePlugins = [];
    }
  }
  onFavoriteThemesChanged(newValue) {
    if (newValue) {
      this.favoriteThemes = JSON.parse(newValue);
    } else {
      this.favoriteThemes = [];
    }
  }
  onInUsePluginsChanged(newValue) {
    if (newValue) {
      this.inUsePlugins = JSON.parse(newValue);
    } else {
      this.inUsePlugins = {};
    }
  }
  onInUseThemesChanged(newValue) {
    if (newValue) {
      this.inUseThemes = JSON.parse(newValue);
    } else {
      this.inUseThemes = {};
    }
  }
  onKnownPluginsChanged(newValue) {
    if (newValue) {
      this.knownPlugins = JSON.parse(newValue);
    } else {
      this.knownPlugins = [];
    }
  }
  onKnownThemesChanged(newValue) {
    if (newValue) {
      this.knownThemes = JSON.parse(newValue);
    } else {
      this.knownThemes = [];
    }
  }
  loadFavoritePlugins() {
    this.favoritePlugins = JSON.parse(localStorage.getItem(this.pluginFavoritesKey) || "[]");
  }
  loadFavoriteThemes() {
    this.favoriteThemes = JSON.parse(localStorage.getItem(this.themeFavoritesKey) || "[]");
  }
  loadInUsePlugins() {
    this.inUsePlugins = JSON.parse(localStorage.getItem(this.pluginInUseKey) || "{}");
  }
  loadInUseThemes() {
    this.inUseThemes = JSON.parse(localStorage.getItem(this.themeInUseKey) || "{}");
  }
  loadKnownPlugins() {
    this.knownPlugins = JSON.parse(localStorage.getItem(this.pluginKnownKey) || "[]");
  }
  loadKnownThemes() {
    this.knownThemes = JSON.parse(localStorage.getItem(this.themeKnownKey) || "[]");
  }
  loadLists() {
    this.loadFavoritePlugins();
    this.loadFavoriteThemes();
    this.loadInUsePlugins();
    this.loadInUseThemes();
    this.loadKnownPlugins();
    this.loadKnownThemes();
  }
  saveFavoritePlugins() {
    if (this.favoritePlugins.length > 0) {
      localStorage.setItem(this.pluginFavoritesKey, JSON.stringify(this.favoritePlugins));
    } else {
      localStorage.removeItem(this.pluginFavoritesKey);
    }
  }
  saveFavoriteThemes() {
    if (this.favoriteThemes.length > 0) {
      localStorage.setItem(this.themeFavoritesKey, JSON.stringify(this.favoriteThemes));
    } else {
      localStorage.removeItem(this.themeFavoritesKey);
    }
  }
  saveInUsePlugins() {
    if (Object.keys(this.inUsePlugins).length > 0) {
      localStorage.setItem(this.pluginInUseKey, JSON.stringify(this.inUsePlugins));
    } else {
      localStorage.removeItem(this.pluginInUseKey);
    }
  }
  saveInUseThemes() {
    if (Object.keys(this.inUseThemes).length > 0) {
      localStorage.setItem(this.themeInUseKey, JSON.stringify(this.inUseThemes));
    } else {
      localStorage.removeItem(this.themeInUseKey);
    }
  }
  saveKnownPlugins() {
    if (this.knownPlugins.length > 0) {
      localStorage.setItem(this.pluginKnownKey, JSON.stringify(this.knownPlugins));
    } else {
      localStorage.removeItem(this.pluginKnownKey);
    }
  }
  saveKnownThemes() {
    if (this.knownThemes.length > 0) {
      localStorage.setItem(this.themeKnownKey, JSON.stringify(this.knownThemes));
    } else {
      localStorage.removeItem(this.themeKnownKey);
    }
  }
  saveLists() {
    this.saveFavoritePlugins();
    this.saveFavoriteThemes();
    this.saveInUsePlugins();
    this.saveInUseThemes();
    this.saveKnownPlugins();
    this.saveKnownThemes();
  }
  updateListsForVault() {
    const currentVault = this.app.appId;
    for (const id of Object.keys(this.app.plugins.manifests)) {
      if (!this.knownPlugins.contains(id)) {
        this.knownPlugins.push(id);
      }
    }
    for (const id of this.app.plugins.enabledPlugins) {
      if (!this.inUsePlugins[id] || !Array.isArray(this.inUsePlugins[id])) {
        this.inUsePlugins[id] = [];
      }
      if (!this.inUsePlugins[id].contains(currentVault)) {
        this.inUsePlugins[id].push(currentVault);
      }
    }
    for (const id of Object.keys(this.inUsePlugins)) {
      if (Array.isArray(this.inUsePlugins[id]) && this.inUsePlugins[id].contains(currentVault)) {
        if (!this.app.plugins.enabledPlugins.has(id)) {
          this.inUsePlugins[id].remove(currentVault);
          if (this.inUsePlugins[id].length <= 0) {
            delete this.inUsePlugins[id];
          }
        }
      }
    }
    for (const name2 of Object.keys(this.app.customCss.themes)) {
      if (!this.knownThemes.contains(name2)) {
        this.knownThemes.push(name2);
      }
    }
    const name = this.app.customCss.theme;
    if (name !== "") {
      if (!this.inUseThemes[name] || !Array.isArray(this.inUseThemes[name])) {
        this.inUseThemes[name] = [];
      }
      if (!this.inUseThemes[name].contains(currentVault)) {
        this.inUseThemes[name].push(currentVault);
      }
    }
    for (const name2 of Object.keys(this.inUseThemes)) {
      if (Array.isArray(this.inUseThemes[name2]) && this.inUseThemes[name2].contains(currentVault)) {
        if (this.app.customCss.theme !== name2) {
          this.inUseThemes[name2].remove(currentVault);
          if (this.inUseThemes[name2].length <= 0) {
            delete this.inUseThemes[name2];
          }
        }
      }
    }
    this.saveLists();
  }
};

/* nosourcemap */